---
- name: Import MongoDB public GPG key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: Add MongoDB repo
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/5.0 multiverse"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install MongoDB packages
  ansible.builtin.apt:
    name:
      - mongodb-org
    state: present

- name: Enable and start MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
