---
- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb
    state: present
    update_cache: yes

- name: Configure MongoDB
  ansible.builtin.lineinfile:
    path: /etc/mongodb.conf
    regexp: '^bind_ip'
    line: 'bind_ip = 0.0.0.0'

- name: Start service
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: yes
