apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: mern-app
spec:
  type: LoadBalancer
  selector:
    app: mern-webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
