apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-webserver
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-webserver
  template:
    metadata:
      labels:
        app: mern-webserver
    spec:
      containers:
      - name: webserver
        image: <dockerhub-username>/mern-webserver:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/mernapp"
